### Importing Necessary Libraries

In [1]:
import os
import pandas as pd
import numpy as np

#### The os.listdir() function returns a list of all the files and directories in the specified directory. The if ".TXT" not in i condition checks if the filename does not contain the substring ".TXT", which suggests that only directories will be added to the folder_name list.

In [2]:
folder_name=[]
for i in os.listdir(r"D:\Data Science\Dataset\bbc"):
    if ".TXT" not in i:
        folder_name.append(i)
folder_name    

['business', 'entertainment', 'politics', 'sport', 'tech']

####  creating a dataset of the text contents of all the .txt files in the bbc subdirectories. However, it is important to note that the script assumes that all the files in the specified path have the .txt extension. If there are any files with other extensions, they will not be included in the dataset. Additionally, the script assumes that all the files can be opened and read successfully, which may not always be the case.

In [3]:
dataset=[]
new_dataset=[]
import glob
for i in folder_name:
    for j in glob.glob("D:\\Data Science\\Dataset\\bbc\\"+i+"\\*.txt"):
        f=open(j)
        dataset.append([i,j.split("\\")[-1],f.read()])
        new_dataset.append([f.read()])

In [4]:
dataset=pd.DataFrame(np.array(dataset))

In [5]:
dataset.head()

0        1                                                  2
0  business  001.txt  Ad sales boost Time Warner profit\n\nQuarterly...
1  business  002.txt  Dollar gains on Greenspan speech\n\nThe dollar...
2  business  003.txt  Yukos unit buyer faces loan claim\n\nThe owner...
3  business  004.txt  High fuel prices hit BA's profits\n\nBritish A...
4  business  005.txt  Pernod takeover talk lifts Domecq\n\nShares in...

In [6]:
dataset.shape

(2224, 3)

In [7]:
dataset[0].value_counts()

sport            511
business         510
politics         416
tech             401
entertainment    386
Name: 0, dtype: int64

In [8]:
y=dataset[0]
x=dataset[2]

In [9]:
dummy_table=pd.get_dummies(y)

In [10]:
dataset.columns=['y','file name','x']

In [11]:
for i in dummy_table:
    dataset[i]=dummy_table[i]

In [12]:
dataset.head()

y file name                                                  x  \
0  business   001.txt  Ad sales boost Time Warner profit\n\nQuarterly...   
1  business   002.txt  Dollar gains on Greenspan speech\n\nThe dollar...   
2  business   003.txt  Yukos unit buyer faces loan claim\n\nThe owner...   
3  business   004.txt  High fuel prices hit BA's profits\n\nBritish A...   
4  business   005.txt  Pernod takeover talk lifts Domecq\n\nShares in...   

   business  entertainment  politics  sport  tech  
0         1              0         0      0     0  
1         1              0         0      0     0  
2         1              0         0      0     0  
3         1              0         0      0     0  
4         1              0         0      0     0

In [13]:
dataset.shape

(2224, 8)

In [14]:
d1=dataset[dataset[i]==1]
d1

y file name                                                  x  \
1823  tech   001.txt  Ink helps drive democracy in Asia\n\nThe Kyrgy...   
1824  tech   002.txt  China net cafe culture crackdown\n\nChinese au...   
1825  tech   003.txt  Microsoft seeking spyware trojan\n\nMicrosoft ...   
1826  tech   004.txt  Digital guru floats sub-$100 PC\n\nNicholas Ne...   
1827  tech   005.txt  Technology gets the creative bug\n\nThe hi-tec...   
...    ...       ...                                                ...   
2219  tech   397.txt  BT program to beat dialler scams\n\nBT is intr...   
2220  tech   398.txt  Spam e-mails tempt net shoppers\n\nComputer us...   
2221  tech   399.txt  Be careful how you code\n\nA new European dire...   
2222  tech   400.txt  US cyber security chief resigns\n\nThe man mak...   
2223  tech   401.txt  Losing yourself in online gaming\n\nOnline rol...   

      business  entertainment  politics  sport  tech  
1823         0              0         0      0     1  
1824         0              0         0      0     1  
1825         0              0         0      0     1  
1826         0              0         0      0     1  
1827         0              0         0      0     1  
...        ...            ...       ...    ...   ...  
2219         0              0         0      0     1  
2220         0              0         0      0     1  
2221         0              0         0      0     1  
2222         0              0         0      0     1  
2223         0              0         0      0     1  

[401 rows x 8 columns]

In [15]:
d2=dataset[dataset[i]!=1].sample(d1.shape[0])
d2

y file name  \
1782          sport   471.txt   
805   entertainment   296.txt   
1412          sport   101.txt   
954        politics   059.txt   
326        business   327.txt   
...             ...       ...   
1128       politics   233.txt   
1599          sport   288.txt   
741   entertainment   232.txt   
1517          sport   206.txt   
1532          sport   221.txt   

                                                      x  business  \
1782  Capriati out of Australian Open\n\nJennifer Ca...         0   
805   Snow Patrol bassist exits group\n\nSnow Patrol...         0   
1412  Man City 0-2 Man Utd\n\nManchester United redu...         0   
954   'Debate needed' on donations cap\n\nA cap on d...         0   
326   Cannabis hopes for drug firm\n\nA prescription...         1   
...                                                 ...       ...   
1128  'Few ready' for information act\n\nThousands o...         0   
1599  Lewsey puzzle over disallowed try\n\nEngland's...         0   
741   Connick Jr to lead Broadway show\n\nSinger and...         0   
1517  Anelka 'eyes Man City departure'\n\nStriker Ni...         0   
1532  Lennon brands Rangers favourites\n\nCeltic's N...         0   

      entertainment  politics  sport  tech  
1782              0         0      1     0  
805               1         0      0     0  
1412              0         0      1     0  
954               0         1      0     0  
326               0         0      0     0  
...             ...       ...    ...   ...  
1128              0         1      0     0  
1599              0         0      1     0  
741               1         0      0     0  
1517              0         0      1     0  
1532              0         0      1     0  

[401 rows x 8 columns]

In [16]:
final_dataset=d1.append(d2)
final_dataset

y file name  \
1823           tech   001.txt   
1824           tech   002.txt   
1825           tech   003.txt   
1826           tech   004.txt   
1827           tech   005.txt   
...             ...       ...   
1128       politics   233.txt   
1599          sport   288.txt   
741   entertainment   232.txt   
1517          sport   206.txt   
1532          sport   221.txt   

                                                      x  business  \
1823  Ink helps drive democracy in Asia\n\nThe Kyrgy...         0   
1824  China net cafe culture crackdown\n\nChinese au...         0   
1825  Microsoft seeking spyware trojan\n\nMicrosoft ...         0   
1826  Digital guru floats sub-$100 PC\n\nNicholas Ne...         0   
1827  Technology gets the creative bug\n\nThe hi-tec...         0   
...                                                 ...       ...   
1128  'Few ready' for information act\n\nThousands o...         0   
1599  Lewsey puzzle over disallowed try\n\nEngland's...         0   
741   Connick Jr to lead Broadway show\n\nSinger and...         0   
1517  Anelka 'eyes Man City departure'\n\nStriker Ni...         0   
1532  Lennon brands Rangers favourites\n\nCeltic's N...         0   

      entertainment  politics  sport  tech  
1823              0         0      0     1  
1824              0         0      0     1  
1825              0         0      0     1  
1826              0         0      0     1  
1827              0         0      0     1  
...             ...       ...    ...   ...  
1128              0         1      0     0  
1599              0         0      1     0  
741               1         0      0     0  
1517              0         0      1     0  
1532              0         0      1     0  

[802 rows x 8 columns]

### Modelling

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
predicted_proba=[]
for i in dataset['y'].unique():
    d1=dataset[dataset[i]==1]
    d2=dataset[dataset[i]!=1].sample(d1.shape[0])
    final_dataset=d1.append(d2)
    x=final_dataset['x']
    y=final_dataset[i]
    from sklearn.metrics import confusion_matrix,accuracy_score
    from sklearn.feature_extraction.text import TfidfVectorizer
    vectorizer = TfidfVectorizer()
    vectorizer.fit(x)
    transformed_x=vectorizer.transform(x)
    print(i,x.shape,y.shape)
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(transformed_x, y, test_size=0.2)
    print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)
    lr=LogisticRegression()
    lr.fit(X_train,y_train)
    print("predicting for category",i)
    print(confusion_matrix(y_test,lr.predict(X_test)))
    print(accuracy_score(y_test,lr.predict(X_test)))
    predicted_proba.append(lr.predict_proba(X_test))
    
    print("*****************************************")
    
    print("                        ")

business (1020,) (1020,)
(816, 20500) (204, 20500) (816,) (204,)
predicting for category business
[[103   2]
 [  5  94]]
0.9656862745098039
*****************************************
                        
entertainment (772,) (772,)
(617, 18695) (155, 18695) (617,) (155,)
predicting for category entertainment
[[77  1]
 [ 7 70]]
0.9483870967741935
*****************************************
                        
politics (832,) (832,)
(665, 18658) (167, 18658) (665,) (167,)
predicting for category politics
[[90  1]
 [ 4 72]]
0.9700598802395209
*****************************************
                        
sport (1022,) (1022,)
(817, 20093) (205, 20093) (817,) (205,)
predicting for category sport
[[103   0]
 [  1 101]]
0.9951219512195122
*****************************************
                        
tech (802,) (802,)
(641, 18610) (161, 18610) (641,) (161,)
predicting for category tech
[[73  2]
 [ 3 83]]
0.968944099378882
*****************************************
             

In [19]:
predicted_proba=np.array(predicted_proba)

In [20]:
predicted_proba.shape

(5,)

In [21]:
predicted_proba[0].shape

(204, 2)

In [22]:
predicted_proba[1].shape,predicted_proba[2].shape,predicted_proba[3].shape

((155, 2), (167, 2), (205, 2))

In [23]:
predicted_proba[0][:,1][0:5]

array([0.85337633, 0.84792131, 0.89460245, 0.26508325, 0.10323847])

In [24]:
predicted_proba[1][:,1][0:5]

array([0.37985278, 0.31896351, 0.19580796, 0.24016397, 0.26713765])

In [25]:
predicted_proba[2][:,1][0:5]

array([0.15517722, 0.36440215, 0.51364067, 0.89953251, 0.25830429])